services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: enviloup_videos_dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - enviloup_void_sex_network

networks:
  enviloup_void_sex_network:
    external: true