version: '3.8'

volumes:
  next_static_data:
  app_public_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: enviloup_videos
    restart: unless-stopped

    environment:
      - NODE_ENV=production
    volumes:
      - next_static_data:/app/.next/static
      - app_public_data:/app/public
    # expose:
    #   - "3000" 
    networks:
      - enviloup_void_sex_network

  nginx:
    image: nginx:alpine 
    container_name: nginx_reverse_proxy
    hostname: cdn.enviloup.localhost
    restart: unless-stopped
    ports:
      - "8085:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./nginx/conf.d/cdn.enviloup.conf:/etc/nginx/conf.d/cdn.enviloup.conf:ro
      - ./public/media:/var/www/media:ro
      - app_public_data:/var/www/html/public:ro
      - next_static_data:/var/www/html/_next/static:ro
    depends_on:
      - app
    networks:
      - enviloup_void_sex_network

networks:
  enviloup_void_sex_network:
    attachable: true
