FROM oven/bun:1-slim AS builder
WORKDIR /app

COPY package.json bun.lockb* tsconfig.json* next.config.*js ./
COPY next-env.d.ts* ./

RUN bun install --frozen-lockfile

COPY . .

RUN bun run build

FROM oven/bun:1-slim AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY package.json bun.lockb* ./

RUN bun install --production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.*js ./

EXPOSE 3000

CMD ["bun", "run", "start"]